services:
  cpp-container:
    build: .
    volumes:
      - .:/app
    command: >
      sh -c "./venv/bin/activate && 
      touch /app/build/ &&
      conan install /app --build=missing && 
      cd /app/build/Release/generators/ &&
      cmake /app -DCMAKE_TOOLCHAIN_FILE='/app/build/Release/generators/conan_toolchain.cmake' -DCMAKE_BUILD_TYPE='Release' &&
      cmake --build . --config Release &&
      /app/build/Release/generators/adaptiveSubtraction.Test &&
      mv /app/build/Release/generators/AdaptiveSubtractionMain /app/release/AdaptiveSubtractionMain && 
      cd /app/release/ &&
      /app/release/AdaptiveSubtractionMain"
    #deploy:
    #  resources:
    #    reservations:
    #      devices:
    #        - driver: nvidia
    #          count: all
    #          capabilities:
    #            - gpu
    #stdin_open: true
    #tty: true
    #image: cpp-container
    #environment:
    #  - ROC_ENABLE=1  # Enable AMD ROCm support
    #devices:
    #  - /dev/kfd  # Kernel Fusion Driver for AMD
    #  - /dev/dri  # Direct Rendering Interface for GPU access


